### ISSUE TITLE
Potential to easily increase performance 

### ISSUE THREAD

**Issue by laundmo** [bagnalla/newton_bevy#1]
hey there, i read your article and there's a potential simple performance increase.

bevy, when iterating over queries, can parallelise those loops too (similar to rayon).
see this example: https://github.com/bevyengine/bevy/blob/main/examples/ecs/parallel_query.rs

Thanks for writing it, always interesting to see people's first impression of Bevy.

**Comment by bagnalla** [comment]
Is there an analogue for [iterating over combinations](https://docs.rs/bevy/latest/bevy/prelude/struct.QueryState.html#method.iter_combinations_mut)? I could see there being a problem with multiple threads accessing the same entity at the same time (since each entity is handled n-1 times where n is the number of entities in the query).
